spring:
  datasource:
    username: sa
    password: 123456
    url: jdbc:sqlserver://localhost:1433;DatabaseName=HotelRoom_Management
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource

    #druid监控地址：http://127.0.0.1:8080/druid/index.html
    druid:
      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      #当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉监控界面sql无法统计，"wall"用于防火墙
      filters: stat,wall
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet:
        url-pattern: "/druid/*"
        enabled: true
        login-username: admin
        login-password: 123456

  #国际化
  messages:
    basename: i18n.login

  #开启put请求的过滤器
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    format:
      date: yyyy-MM-dd

  thymeleaf:
    cache: false

  #热部署
  devtools:
    restart:
      enabled: true


